/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.vikas.test.mavenaws.api;

import java.util.Optional;

import javax.validation.Valid;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import com.vikas.test.mavenaws.api.model.error.ErrorResponse;
import com.vikas.test.mavenaws.api.model.request.CustomerCreationRequest;
import com.vikas.test.mavenaws.api.model.request.CustomerUpdateRequest;
import com.vikas.test.mavenaws.api.model.response.CustomerDetailsResponse;
import com.vikas.test.mavenaws.api.util.ApiUtil;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-01-05T17:29:07.890+05:30[Asia/Calcutta]")

@Validated
@Api(value = "customer", description = "the customer API")
public interface Customer {

	default Optional<NativeWebRequest> getRequest() {
		return Optional.empty();
	}

	@ApiOperation(value = "Add new Customer", nickname = "addCustomer", notes = "Add new customer which has admin role", tags = {
			"customer", })
	@ApiResponses(value = { @ApiResponse(code = 202, message = "Customer Sucessfully Added"),
			@ApiResponse(code = 400, message = "Invalid ID supplied", response = ErrorResponse.class),
			@ApiResponse(code = 404, message = "customer not found", response = ErrorResponse.class),
			@ApiResponse(code = 405, message = "Validation exception", response = ErrorResponse.class),
			@ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class),
			@ApiResponse(code = 200, message = "successful operation") })
	@RequestMapping(value = "/customer", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.POST)
	default ResponseEntity<Void> addCustomer(
			@ApiParam(value = "enter the appropriate customer creation Request", required = true) @Valid @RequestBody CustomerCreationRequest customerCreationRequest) {
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

	}

	@ApiOperation(value = "Deletes a Customer", nickname = "deleteCustomerById", notes = "Deletes a Customer and underlying details", tags = {
			"customer", })
	@ApiResponses(value = { @ApiResponse(code = 202, message = "Customer Deleted Sucessfully"),
			@ApiResponse(code = 400, message = "Invalid ID supplied", response = ErrorResponse.class),
			@ApiResponse(code = 404, message = "customer not found", response = ErrorResponse.class),
			@ApiResponse(code = 405, message = "Validation exception", response = ErrorResponse.class),
			@ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class),
			@ApiResponse(code = 200, message = "successful operation") })
	@RequestMapping(value = "/customer/{customerId}", produces = { "application/json" }, method = RequestMethod.DELETE)
	default ResponseEntity<Void> deleteCustomerById(
			@ApiParam(value = "ID of customer to return", required = true) @PathVariable("customerId") Long customerId) {
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

	}

	@ApiOperation(value = "Find customer by ID", nickname = "getCustomerById", notes = "Returns a single customer", response = CustomerDetailsResponse.class, tags = {
			"customer", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "Customer Details Fetched Successfully", response = CustomerDetailsResponse.class),
			@ApiResponse(code = 400, message = "Invalid ID supplied", response = ErrorResponse.class),
			@ApiResponse(code = 404, message = "customer not found", response = ErrorResponse.class),
			@ApiResponse(code = 405, message = "Validation exception", response = ErrorResponse.class),
			@ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class),
			@ApiResponse(code = 200, message = "successful operation") })
	@RequestMapping(value = "/customer/{customerId}", produces = { "application/json" }, method = RequestMethod.GET)
	default ResponseEntity<CustomerDetailsResponse> getCustomerById(
			@ApiParam(value = "ID of customer to return", required = true) @PathVariable("customerId") Long customerId) {
		getRequest().ifPresent(request -> {
			for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
				if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
					ApiUtil.setExampleResponse(request, "application/json",
							"{  \"createdAt\" : \"createdAt\",  \"hsmUserId\" : \"hsmUserId\",  \"customerUUID\" : \"customerUUID\",  \"contactEmail\" : \"contactEmail\",  \"contactName\" : \"contactName\",  \"companyName\" : \"companyName\",  \"contactNumber\" : 1111111111,  \"publicKeyConfirmed\" : true,  \"id\" : 0,  \"type\" : [ null, null ],  \"version\" : 1,  \"updatedAt\" : \"updatedAt\"}");
					break;
				}
			}
		});
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

	}

	@ApiOperation(value = "Update an existing customer", nickname = "updateCustomer", notes = "Update an existing known customer", tags = {
			"customer", })
	@ApiResponses(value = { @ApiResponse(code = 202, message = "Customer Sucessfully Updated"),
			@ApiResponse(code = 400, message = "Invalid ID supplied", response = ErrorResponse.class),
			@ApiResponse(code = 404, message = "customer not found", response = ErrorResponse.class),
			@ApiResponse(code = 405, message = "Validation exception", response = ErrorResponse.class),
			@ApiResponse(code = 500, message = "Internal Server Error", response = ErrorResponse.class),
			@ApiResponse(code = 200, message = "successful operation") })
	@RequestMapping(value = "/customer", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.PUT)
	default ResponseEntity<Void> updateCustomer(
			@ApiParam(value = "customer update request", required = true) @Valid @RequestBody CustomerUpdateRequest customerUpdateRequest) {
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

	}

}
