logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
server:
  port: 7070
spring:
  application:
    admin:
      enabled: true
  datasource:
    continue-on-error: false
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: ALWAYS
    url: jdbc:postgresql://localhost:5432/awsservicestest
    username: postgres
    password: great123
#    ddl-auto: create
  devtools:
    add-properties: false
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  profiles:
    active: dev